name: Docker Image CI

on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and push'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: https://quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and Push
      run: |
        docker build -t ${{ github.repository }}:${{ github.ref_name }} .
        docker push ${{ github.repository }}:${{ github.ref_name }}
