name: Docker Image CI

on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and push'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Get Tag
      id: tag
      shell: pwsh
      run: |
        $tag = "REGISTRY_IMAGE=quay.io/" + ($env:GITHUB_REPOSITORY).ToLower() 
        write-host $tag
        $tag >> $env:GITHUB_OUTPUT


    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch || github.ref_name }}
        
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.tag.outputs.REGISTRY_IMAGE }}:${{ github.ref_name }}